-- 创建卖家信息表外键 SELLER_INFO_FK_PAYPAL_INFO_ID  SELLER_INFO_FK_PEOPLE_INFO_ID  --
ALTER TABLE SELLER_INFO ADD CONSTRAINT SELLER_INFO_FK_PAYPAL_INFO_ID FOREIGN KEY (PAYPAL_INFO_ID) REFERENCES PAYPAL_INFO (ID);

ALTER TABLE SELLER_INFO ADD CONSTRAINT SELLER_INFO_FK_PEOPLE_INFO_ID FOREIGN KEY (PEOPLE_INFO_ID) REFERENCES PEOPLE_INFO (ID);

-- 创建订单支付流水信息表外键 ORDER_STATEMENT_INFO_FK_ORDER_INFO_ID  ORDER_STATEMENT_INFO_FK_PAYPAL_INFO_ID  --
ALTER TABLE ORDER_STATEMENT_INFO ADD CONSTRAINT ORDER_STATEMENT_INFO_FK_ORDER_INFO_ID FOREIGN KEY (ORDER_INFO_ID) REFERENCES ORDER_INFO (ID);

ALTER TABLE ORDER_STATEMENT_INFO ADD CONSTRAINT ORDER_STATEMENT_INFO_FK_PAYPAL_INFO_ID FOREIGN KEY (PAYPAL_INFO_ID) REFERENCES PAYPAL_INFO (ID);

-- 创建订单信息外键 --
ALTER TABLE ORDER_INFO ADD CONSTRAINT ORDER_INFO_FK_BUYER_INFO_ID FOREIGN KEY (BUYER_INFO_ID) REFERENCES BUYER_INFO (ID);

-- 创建订单详情外键 --
ALTER TABLE ORDER_DETAIL ADD CONSTRAINT ORDER_DETAIL_FK_ORDER_INFO_ID FOREIGN KEY (ORDER_INFO_ID) REFERENCES ORDER_INFO (ID);

ALTER TABLE ORDER_DETAIL ADD CONSTRAINT ORDER_DETAIL_FK_ITEM_INFO_ID FOREIGN KEY (ITEM_INFO_ID) REFERENCES ITEM_INFO (ID);

-- 创建买家信息外键
ALTER TABLE BUYER_INFO ADD CONSTRAINT BUYER_INFO_FK_PAYPAL_INFO_ID FOREIGN KEY (PAYPAL_INFO_ID) REFERENCES PAYPAL_INFO (ID);

ALTER TABLE BUYER_INFO ADD CONSTRAINT BUYER_INFO_FK_PEOPLE_INFO_ID FOREIGN KEY (PEOPLE_INFO_ID) REFERENCES PEOPLE_INFO (ID);

-- 创建淘宝账户外键 
ALTER TABLE TAOBAO_ACCOUNT ADD CONSTRAINT TAOBAO_ACCOUNT_FK_GRADE_ID FOREIGN KEY (GRADE_ID) REFERENCES GRADE(ID);
ALTER TABLE TAOBAO_ACCOUNT ADD CONSTRAINT TAOBAO_ACCOUNT_FK_PEOPLE_INFO_ID FOREIGN KEY (PEOPLE_INFO_ID) REFERENCES PEOPLE_INFO(ID);

-- 删除外键
ALTER TABLE BUYER_INFO DROP FOREIGN KEY BUYER_INFO_FK_PAYPAL_INFO_ID;

ALTER TABLE BUYER_INFO DROP FOREIGN KEY BUYER_INFO_FK_PEOPLE_INFO_ID;

ALTER TABLE ORDER_DETAIL DROP FOREIGN KEY ORDER_DETAIL_FK_ORDER_INFO_ID;

ALTER TABLE ORDER_DETAIL DROP FOREIGN KEY ORDER_DETAIL_FK_ITEM_INFO_ID;

ALTER TABLE ORDER_INFO DROP FOREIGN KEY ORDER_INFO_FK_BUYER_INFO_ID;

ALTER TABLE ORDER_STATEMENT_INFO DROP FOREIGN KEY ORDER_STATEMENT_INFO_FK_ORDER_INFO_ID;

ALTER TABLE ORDER_STATEMENT_INFO DROP FOREIGN KEY ORDER_STATEMENT_INFO_FK_PAYPAL_INFO_ID;

ALTER TABLE SELLER_INFO DROP FOREIGN KEY SELLER_INFO_FK_PAYPAL_INFO_ID;

ALTER TABLE SELLER_INFO DROP FOREIGN KEY SELLER_INFO_FK_PEOPLE_INFO_ID;
